config/routes.rb
Books::Application.routes.draw do
  resources :reviews

  resources :users

  resources :publishers

  resources :books

  resources :genres

  resources :authors

  resources :book_authors

  resources :book_genres

  resources :users

  resources :sessions, :only => [:new, :create]

  resources :volumes, only:[:index, :show]

  root 'books#index'

  get 'signup' => 'users#new'

  get 'signin' => 'sessions#new'

  post 'volumes', to:'volumes#search'

  delete 'signout' => 'sessions#destroy'
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :book_authors
  has_many :authors, through: :book_authors
  has_many :book_genres
  has_many :genres, through: :book_genres
  has_many :reviews
  has_many :users, through: :reviews
  belongs_to :publisher
  def to_s
    name
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :plot)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :plot %><br>
    <%= f.text_area :plot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

<br />

<%= link_to 'Edit authors', book_authors_path(params: {book_id: @book.id})  %> |
<%= link_to 'Edit genres', book_genres_path(params: {book_id: @book.id})  %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<p>
  Number of books:
  <%= @books.count %>
</p>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.name, book %></td>
        <td><%= edit_and_destroy_buttons(book) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to('New book', new_book_path, class:"btn btn-default") unless current_user.nil? %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @book.name %>
</h1>

<% unless @book.publisher.nil? %>
    Published by <%= link_to @book.publisher.name, @book.publisher %>
<% end %>

<% unless @book.authors.empty? %>
    <p>Authors
      <% @book.authors.each do |author| %>
          <%= link_to author.name, author %>
      <%end%>
    </p>
<%end%>

<% unless @book.authors.empty? %>
    <p>Genres
      <% @book.genres.each do |genre| %>
          <%= link_to genre.name, genre %>
      <%end%>
    </p>
<%end%>

<p>
  <%= @book.plot %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>