config/routes.rb
Books::Application.routes.draw do
  resources :reviews

  resources :users

  resources :publishers

  resources :books

  resources :genres

  resources :authors

  resources :book_authors

  resources :book_genres

  resources :users

  resources :sessions, :only => [:new, :create]

  resources :volumes, only:[:index, :show]

  root 'books#index'

  get 'signup' => 'users#new'

  get 'signin' => 'sessions#new'

  post 'volumes', to:'volumes#search'

  delete 'signout' => 'sessions#destroy'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Authors', authors_path %></li>
<li><%= link_to 'Publishers', publishers_path %></li>
<li><%= link_to 'Users', users_path %></li>
<li><%= link_to 'Genres', genres_path %></li>
<% unless current_user.nil? %>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <%= current_user.username %> <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "My page", current_user %></li>
        <li><%= link_to 'Sign out', signout_path, method: :delete %></li>
      </ul>
<% else %>
    <li><%= link_to 'Sign in', signin_path %></li>
    <li><%= link_to 'Sign up', signup_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Books" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ratebeer" %>">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>
<main role="main" class="container">
  <%= render 'layouts/messages' %>

  <div class="row">
    <div class="col-md-8">
      <%= yield %>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</main>
</body>
</html>